import type { CategoryDef } from './types.ts';

// Built-in checks. Keywords are English plus Filipino/Taglish terms common on
// PH promo pages (the small local model only handles EN output reliably, so the keyword
// rules carry the Tagalog coverage).
export const BUILTIN_CATEGORIES: CategoryDef[] = [
  {
    id: 'payment_upfront',
    label: 'Payment upfront',
    description: 'The page asks for money before the reward: a fee, shipping, deposit or processing charge.',
    icon: 'Banknote',
    keywords: ['pay', 'payment', 'processing fee', 'shipping fee', 'handling fee', 'service fee', 'convenience fee', 'deposit', 'send money', 'transfer', 'bayad', 'bayaran', 'magbayad', 'singil', 'pambayad'],
    formSignals: [],
    weight: 3,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'card_details',
    label: 'Card details',
    description: 'The page asks for credit or debit card numbers, expiry or CVV.',
    icon: 'CreditCard',
    keywords: ['credit card', 'debit card', 'card number', 'card details', 'cvv', 'cvc', 'card expiry', 'billing', 'visa', 'mastercard'],
    formSignals: ['card'],
    weight: 3,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'bank_ewallet',
    label: 'Bank or e-wallet',
    description: 'The page involves a bank account or an e-wallet such as GCash or Maya.',
    icon: 'Landmark',
    keywords: ['gcash', 'maya', 'paymaya', 'bank account', 'online banking', 'bank login', 'e-wallet', 'ewallet', 'unionbank', 'bdo', 'bpi', 'metrobank', 'rcbc', 'landbank', 'account number'],
    formSignals: ['bank'],
    weight: 3,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'otp_pin',
    label: 'OTP or PIN',
    description: 'The page asks for a one-time PIN, verification code or MPIN — a strong scam signal.',
    icon: 'KeyRound',
    keywords: ['otp', 'one-time pin', 'one time pin', 'one-time password', 'verification code', 'mpin', '6-digit code', '6 digit code', 'security code sent', 'code sent to your'],
    formSignals: ['otp'],
    weight: 3,
    trustWeight: 3,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'mobile_number',
    label: 'Mobile number',
    description: 'The page asks for a mobile or contact number.',
    icon: 'Phone',
    keywords: ['mobile number', 'phone number', 'cellphone', 'contact number', '+63', 'numero', 'telepono', 'mobile no'],
    formSignals: ['tel'],
    weight: 1,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'government_id',
    label: 'Government ID',
    description: 'The page asks for an official ID or a selfie, such as a valid ID, PhilSys, passport or UMID.',
    icon: 'IdCard',
    keywords: ['valid id', 'government id', 'government-issued', 'philsys', 'national id', 'passport', "driver's license", 'drivers license', 'umid', 'tin', 'sss', 'selfie', 'photo id', 'upload your id', 'id verification', 'proof of identity'],
    formSignals: ['file'],
    weight: 3,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'subscription',
    label: 'Subscription or renewal',
    description: 'The offer turns into a paid subscription or auto-renews.',
    icon: 'Repeat',
    keywords: ['auto-renew', 'auto renew', 'autorenew', 'per month', '/mo', 'monthly', 'recurring', 'billed', 'subscription', 'renews', 'cancel anytime', 'charged', 'every month', 'per year', 'annually'],
    formSignals: [],
    weight: 2,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'account_signup',
    label: 'Account signup',
    description: 'The page requires creating an account or registering.',
    icon: 'UserPlus',
    keywords: ['sign up', 'signup', 'register', 'create account', 'create an account', 'log in', 'login', 'magparehistro', 'magrehistro', 'mag-sign up', 'mag-signup'],
    formSignals: ['password'],
    weight: 1,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'app_download',
    label: 'App download',
    description: 'Claiming the offer requires downloading or installing an app.',
    icon: 'Download',
    keywords: ['download the app', 'download now', 'i-download', 'idownload', 'app store', 'google play', 'install the app', 'get the app', 'play store'],
    formSignals: [],
    weight: 1,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'minimum_spend',
    label: 'Minimum spend',
    description: 'The reward needs a minimum purchase or spend amount.',
    icon: 'ShoppingBag',
    keywords: ['minimum spend', 'minimum purchase', 'min. spend', 'min spend', 'spend at least', 'minimum of', 'purchase of', 'worth of', 'single receipt'],
    formSignals: [],
    weight: 2,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'social_share_referral',
    label: 'Share or refer',
    description: 'The page asks you to share, post, tag or invite friends.',
    icon: 'Share2',
    keywords: ['share this', 'share on', 'referral', 'refer a friend', 'invite friends', 'tag your friends', 'tag 3 friends', 'post about', 'follow and share', 'i-share', 'ishare'],
    formSignals: [],
    weight: 1,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'personal_info',
    label: 'Personal details',
    description: 'The page asks for personal information like your full name, address or birthday.',
    icon: 'UserRound',
    keywords: ['full name', 'address', 'birthday', 'birthdate', 'date of birth', 'edad', 'tirahan', 'home address', 'delivery address', 'personal details', 'personal information'],
    formSignals: ['address', 'birthdate'],
    weight: 1,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'in_person',
    label: 'In-person visit',
    description: 'Claiming requires going to a branch, store or physical location.',
    icon: 'Store',
    keywords: ['in-store', 'in store', 'participating stores', 'participating branches', 'visit us', 'claim at', 'physical store', 'store visit', 'sa branch', 'branch near', 'walk-in'],
    formSignals: [],
    weight: 2,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'survey',
    label: 'Survey',
    description: 'The page requires answering a survey or questionnaire.',
    icon: 'ClipboardList',
    keywords: ['survey', 'answer a few questions', 'quick survey', 'questionnaire', 'short survey', 'pagsusuri'],
    formSignals: [],
    weight: 1,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'time_pressure',
    label: 'Urgency pressure',
    description: 'The page uses countdowns, limited slots or deadlines to rush you.',
    icon: 'Timer',
    keywords: ['expires in', 'hurry', 'limited time', 'today only', 'ends soon', 'last chance', 'slots left', 'while supplies last', 'act now', 'offer ends', 'ends tonight', 'countdown', 'hanggang', 'mabilis'],
    formSignals: [],
    weight: 0,
    trustWeight: 1,
    enabled: true,
    builtIn: true,
  },
  {
    id: 'free_plan',
    label: 'Free option',
    description: 'The page offers a genuinely free way to get the reward or use the product.',
    icon: 'BadgeCheck',
    keywords: ['no credit card required', 'no card required', 'free forever', 'free plan', 'free tier', 'walang bayad', 'no payment required', 'always free', 'free of charge'],
    formSignals: [],
    weight: 0,
    trustWeight: 0,
    enabled: true,
    builtIn: true,
    positive: true,
  },
];
